
INSERT INTO City (`id`, `name`)
VALUES (1, 'Aïn Harrouda'),
       (2, 'Ben Yakhlef'),
       (3, 'Bouskoura'),
       (4, 'Casablanca'),
       (5, 'Médiouna'),
       (6, 'Mohammadia'),
       (7, 'Tit Mellil'),
       (8, 'Ben Yakhlef'),
       (9, 'Bejaâd'),
       (10, 'Ben Ahmed'),
       (11, 'Benslimane'),
       (12, 'Berrechid'),
       (13, 'Boujniba'),
       (14, 'Boulanouare'),
       (15, 'Bouznika'),
       (16, 'Deroua'),
       (17, 'El Borouj'),
       (18, 'El Gara'),
       (19, 'Guisser'),
       (20, 'Hattane'),
       (21, 'Khouribga'),
       (22, 'Loulad'),
       (23, 'Oued Zem'),
       (24, 'Oulad Abbou'),
       (25, 'Oulad H''Riz Sahel'),
       (26, 'Oulad M''rah'),
       (27, 'Oulad Saïd'),
       (28, 'Oulad Sidi Ben Daoud'),
       (29, 'Ras El Aïn'),
       (30, 'Settat'),
       (31, 'Sidi Rahhal Chataï'),
       (32, 'Soualem'),
       (33, 'Azemmour'),
       (34, 'Bir Jdid'),
       (35, 'Bouguedra'),
       (36, 'Echemmaia'),
       (37, 'El Jadida'),
       (38, 'Hrara'),
       (39, 'Ighoud'),
       (40, 'Jamâat Shaim'),
       (41, 'Jorf Lasfar'),
       (42, 'Khemis Zemamra'),
       (43, 'Laaounate'),
       (44, 'Moulay Abdallah'),
       (45, 'Oualidia'),
       (46, 'Oulad Amrane'),
       (47, 'Oulad Frej'),
       (48, 'Oulad Ghadbane'),
       (49, 'Safi'),
       (50, 'Sebt El Maârif'),
       (51, 'Sebt Gzoula'),
       (52, 'Sidi Ahmed'),
       (53, 'Sidi Ali Ban Hamdouche'),
       (54, 'Sidi Bennour'),
       (55, 'Sidi Bouzid'),
       (56, 'Sidi Smaïl'),
       (57, 'Youssoufia'),
       (58, 'Fès'),
       (59, 'Aïn Cheggag'),
       (60, 'Bhalil'),
       (61, 'Boulemane'),
       (62, 'El Menzel'),
       (63, 'Guigou'),
       (64, 'Imouzzer Kandar'),
       (65, 'Imouzzer Marmoucha'),
       (66, 'Missour'),
       (67, 'Moulay Yaâcoub'),
       (68, 'Ouled Tayeb'),
       (69, 'Outat El Haj'),
       (70, 'Ribate El Kheir'),
       (71, 'Séfrou'),
       (72, 'Skhinate'),
       (73, 'Tafajight'),
       (74, 'Arbaoua'),
       (75, 'Aïn Dorij'),
       (76, 'Dar Gueddari'),
       (77, 'Had Kourt'),
       (78, 'Jorf El Melha'),
       (79, 'Kénitra'),
       (80, 'Khenichet'),
       (81, 'Lalla Mimouna'),
       (82, 'Mechra Bel Ksiri'),
       (83, 'Mehdia'),
       (84, 'Moulay Bousselham'),
       (85, 'Sidi Allal Tazi'),
       (86, 'Sidi Kacem'),
       (87, 'Sidi Slimane'),
       (88, 'Sidi Taibi'),
       (89, 'Sidi Yahya El Gharb'),
       (90, 'Souk El Arbaa'),
       (91, 'Akka'),
       (92, 'Assa'),
       (93, 'Bouizakarne'),
       (94, 'El Ouatia'),
       (95, 'Es-Semara'),
       (96, 'Fam El Hisn'),
       (97, 'Foum Zguid'),
       (98, 'Guelmim'),
       (99, 'Taghjijt'),
       (100, 'Tan-Tan'),
       (101, 'Tata'),
       (102, 'Zag'),
       (103, 'Marrakech'),
       (104, 'Ait Daoud'),
       (115, 'Amizmiz'),
       (116, 'Assahrij'),
       (117, 'Aït Ourir'),
       (118, 'Ben Guerir'),
       (119, 'Chichaoua'),
       (120, 'El Hanchane'),
       (121, 'El Kelaâ des Sraghna'),
       (122, 'Essaouira'),
       (123, 'Fraïta'),
       (124, 'Ghmate'),
       (125, 'Ighounane'),
       (126, 'Imintanoute'),
       (127, 'Kattara'),
       (128, 'Lalla Takerkoust'),
       (129, 'Loudaya'),
       (130, 'Lâattaouia'),
       (131, 'Moulay Brahim'),
       (132, 'Mzouda'),
       (133, 'Ounagha'),
       (134, 'Sid L''Mokhtar'),
       (135, 'Sid Zouin'),
       (136, 'Sidi Abdallah Ghiat'),
       (137, 'Sidi Bou Othmane'),
       (138, 'Sidi Rahhal'),
       (139, 'Skhour Rehamna'),
       (140, 'Smimou'),
       (141, 'Tafetachte'),
       (142, 'Tahannaout'),
       (143, 'Talmest'),
       (144, 'Tamallalt'),
       (145, 'Tamanar'),
       (146, 'Tamansourt'),
       (147, 'Tameslouht'),
       (148, 'Tanalt'),
       (149, 'Zeubelemok'),
       (150, 'Meknès'),
       (151, 'Khénifra'),
       (152, 'Agourai'),
       (153, 'Ain Taoujdate'),
       (154, 'MyAliCherif'),
       (155, 'Rissani'),
       (156, 'Amalou Ighriben'),
       (157, 'Aoufous'),
       (158, 'Arfoud'),
       (159, 'Azrou'),
       (160, 'Aïn Jemaa'),
       (161, 'Aïn Karma'),
       (162, 'Aïn Leuh'),
       (163, 'Aït Boubidmane'),
       (164, 'Aït Ishaq'),
       (165, 'Boudnib'),
       (166, 'Boufakrane'),
       (167, 'Boumia'),
       (168, 'El Hajeb'),
       (169, 'Elkbab'),
       (170, 'Er-Rich'),
       (171, 'Errachidia'),
       (172, 'Gardmit'),
       (173, 'Goulmima'),
       (174, 'Gourrama'),
       (175, 'Had Bouhssoussen'),
       (176, 'Haj Kaddour'),
       (177, 'Ifrane'),
       (178, 'Itzer'),
       (179, 'Jorf'),
       (180, 'Kehf Nsour'),
       (181, 'Kerrouchen'),
       (182, 'Mhaya'),
       (183, 'Mrirt'),
       (184, 'Midelt'),
       (185, 'Moulay Ali Cherif'),
       (186, 'Moulay Bouazza'),
       (187, 'Moulay Idriss Zerhoun'),
       (188, 'Moussaoua'),
       (189, 'NZalat Bni Amar'),
       (190, 'Ouaoumana'),
       (191, 'Oued Ifrane'),
       (192, 'Sabaa Aiyoun'),
       (193, 'Sebt Jahjouh'),
       (194, 'Sidi Addi'),
       (195, 'Tichoute'),
       (196, 'Tighassaline'),
       (197, 'Tighza'),
       (198, 'Timahdite'),
       (199, 'Tinejdad'),
       (200, 'Tizguite'),
       (201, 'Toulal'),
       (202, 'Tounfite'),
       (203, 'Zaouia d''Ifrane'),
       (204, 'Zaïda'),
       (205, 'Ahfir'),
       (206, 'Aklim'),
       (207, 'Al Aroui'),
       (208, 'Aïn Bni Mathar'),
       (209, 'Aïn Erreggada'),
       (210, 'Ben Taïeb'),
       (211, 'Berkane'),
       (212, 'Bni Ansar'),
       (213, 'Bni Chiker'),
       (214, 'Bni Drar'),
       (215, 'Bni Tadjite'),
       (216, 'Bouanane'),
       (217, 'Bouarfa'),
       (218, 'Bouhdila'),
       (219, 'Dar El Kebdani'),
       (220, 'Debdou'),
       (221, 'Douar Kannine'),
       (222, 'Driouch'),
       (223, 'El Aïoun Sidi Mellouk'),
       (224, 'Farkhana'),
       (225, 'Figuig'),
       (226, 'Ihddaden'),
       (227, 'Jaâdar'),
       (228, 'Jerada'),
       (229, 'Kariat Arekmane'),
       (230, 'Kassita'),
       (231, 'Kerouna'),
       (232, 'Laâtamna'),
       (233, 'Madagh'),
       (234, 'Midar'),
       (235, 'Nador'),
       (236, 'Naima'),
       (237, 'Oued Heimer'),
       (238, 'Oujda'),
       (239, 'Ras El Ma'),
       (240, 'Saidia'),
       (241, 'Selouane'),
       (242, 'Sidi Boubker'),
       (243, 'Sidi Moussa Lemhaya'),
       (244, 'Tafoughalt'),
       (245, 'Taourirt'),
       (246, 'Tendrara'),
       (247, 'Tiztoutine'),
       (248, 'Touima'),
       (249, 'Touissit'),
       (250, 'Tafraout'),
       (251, 'Agadir'),
       (252, 'Aït Melloul'),
       (253, 'Aït Ourir'),
       (254, 'Aoulouz'),
       (255, 'Aourir'),
       (256, 'Arazane'),
       (257, 'Biougra'),
       (258, 'Boumalne'),
       (259, 'Dcheira El Jihadia'),
       (260, 'Drargua'),
       (261, 'Harte Lyamine'),
       (262, 'Ifri'),
       (263, 'Ighrem N''Ougdal'),
       (264, 'Igoudar Mnabha'),
       (265, 'Imassine'),
       (266, 'Inezgane'),
       (267, 'Kelaat-M''Gouna'),
       (268, 'Lakhsas'),
       (269, 'Massa (Maroc)'),
       (270, 'Mirleft'),
       (271, 'N''Zalat Laadam'),
       (272, 'Ouarzazate'),
       (273, 'Oulad Berhil'),
       (274, 'Sarghine'),
       (275, 'Sebt Gzoula'),
       (276, 'Sid L''Mokhtar'),
       (277, 'Sidi Abdallah El Bouchouari'),
       (278, 'Sidi Bibi'),
       (279, 'Sidi Ifni'),
       (280, 'Sidi Ifni'),
       (281, 'Sidi Ifni'),
       (282, 'Tagante'),
       (283, 'Taghazout'),
       (284, 'Tafraout'),
       (285, 'Tafraout'),
       (286, 'Tafraout'),
       (287, 'Tagant'),
       (288, 'Tagzirt'),
       (289, 'Taliouine'),
       (290, 'Tamaloukt'),
       (291, 'Tamegroute'),
       (292, 'Tameslouht'),
       (293, 'Tamsaout'),
       (294, 'Tandelt'),
       (295, 'Tangarfa'),
       (296, 'Tanoumrite Nkob Zagora'),
       (297, 'Tarfaya'),
       (298, 'Taroudannt'),
       (299, 'Temsia'),
       (300, 'Tiflet'),
       (301, 'Tiznit'),
       (302, 'Toundout'),
       (303, 'Zag'),
       (304, 'Zaouia d''Ifrane'),
       (305, 'Zaouïat Saïss'),
       (306, 'Zaouïat Saïss'),
       (307, 'Zerkten'),
       (308, 'Zguida'),
       (309, 'Ksar El Kébir'),
       (310, 'Aïn Taya'),
       (311, 'Baba Hassen'),
       (312, 'Bab El Oued'),
       (313, 'Bir Mourad Raïs'),
       (314, 'Bir Mourad Raïs'),
       (315, 'Birkhadem'),
       (316, 'Bir Mourad Raïs'),
       (317, 'Birtouta'),
       (318, 'Bordj El Kiffan');
